on:
  workflow_call:
    inputs:
      repo_name:
        required: true
      base_branch:
        required: true
        type: string
      compare_branch:
        required: true
        type: string
      pr_number:
        required: true
        type: number
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  main:
    # if: ${{ !startsWith(github.head_ref, 'release-please') && !startsWith(github.head_ref, 'renovate') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: octokit/request-action@v2.x
        id: get_pull_request_info
        with:
          route: GET /repos/{repo}/pulls/{pr}
          repo: ${{ inputs.repo_name }}
          pr: ${{ inputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse pull request using jq and checking mergeable state
        id: mergeable_pr
        run: |
          cat <<EOF > pr.js
          ${{ steps.get_pull_request_info.outputs.data }}
          EOF
          export IS_MERGEABLE_PR=$(jq -r '.mergeable' pr.js)
          echo "mergeable=$IS_MERGEABLE_PR" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3

      - name: Merge the PR
        if: steps.mergeable_pr.outputs.token
        run: |
          git config --user.email "smellen@cerebrum.com"
          git config --user.name "cerebrumcom"
          git checkout ${{ inputs.base_branch }}
          git merge --ff-only ${{ inputs.compare_branch }}
          git push
