on:
  workflow_call:
    inputs:
      github_object:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      pr_number:
        required: true
        type: number
    secrets:
      GITHUB_AUTH_TOKEN:
        required: true

jobs:
  check-for-comment:
    runs-on: ubuntu-20.04
    steps:
      - name: Parse the current GitHub object
        run:
          echo ${{ inputs.github_object }}
  
      - uses: octokit/request-action@v2.x
        id: get_pull_request_info
        with:
          route: GET /repos/{repo}/pulls/{pr}
          repo: ${{ inputs.repo_name }}
          pr: ${{ inputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}

      - name: Parse pull request using jq and checking mergeable state
        id: mergeable_pr
        run: |
          cat <<EOF > pr.js
          ${{ steps.get_pull_request_info.outputs.data }}
          EOF
          export BASE_BRANCH=$(jq -r '.base.ref' pr.js)
          echo "baseBranch=$BASE_BRANCH" >> $GITHUB_OUTPUT
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV

      - uses: octokit/request-action@v2.x
        id: get_pull_request_comments
        with:
          route: GET /repos/{repo}/issues/{pr}/comments
          repo: ${{ inputs.repo_name }}
          pr: ${{ inputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}

      - name: Check base ref, parse comments and check if fast-forward comment exists
        run: |
          if [ "$BASE_BRANCH" != "staging" ] && [ "$BASE_BRANCH" != "production" ]; then
            exit 0
          fi
          cat <<EOF > comments.js
          ${{ steps.get_pull_request_comments.outputs.data }}
          EOF
          COMMENT_EXISTS=$(jq -r '.[] | select(.body=="/fast-forward") | .body' < comments.js)
          echo $COMMENT_EXISTS | grep -q "/fast-forward" 2> /dev/null
          exit $?
