on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      pr_number:
        required: true
        type: number
      base_ref:
        required: true
        type: string
    secrets:
      GITHUB_AUTH_TOKEN:
        required: true

jobs:
  check-for-comment:
    if: ${{ contains(inputs.base_ref, 'staging') || contains(inputs.base_ref, 'production') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: octokit/request-action@v2.x
        id: get_pull_request_comments
        with:
          route: GET /repos/{repo}/issues/{pr}/comments
          repo: ${{ inputs.repo_name }}
          pr: ${{ inputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}

      - name: Parse pull request comments using jq and checking if fast-forward comment exists
        id: comments_pr
        run: |
          cat <<EOF > comments.js
          ${{ steps.get_pull_request_comments.outputs.data }}
          EOF
          COMMENT_EXISTS=$(jq -r '.[] | select(.body=="/fast-forward") | .body')
          echo $COMMENT_EXISTS
          echo $COMMENT_EXISTS | grep -q "/fast-forward" 2> /dev/null
          exit $?
