name: Fast-forward action
on:
  workflow_call:
    secrets:
      GITHUB_AUTH_TOKEN:
        required: true
      MERGEFREEZE_TOKEN:
        required: true

jobs:
  check-for-comment:
    runs-on: ubuntu-latest
    outputs:
      MAINTAINERS_AND_ADMINS: ${{ steps.maintainers_and_admins_list.outputs.MAINTAINERS_AND_ADMINS }}
    env:
      PR: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.event.issue.number }}
    steps:
      - uses: octokit/request-action@v2.x
        id: get_pull_request_info
        with:
          route: GET /repos/{repo}/pulls/{pr}
          repo: ${{ github.repository }}
          pr: ${{ env.PR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}

      - name: Parse pull request using jq and checking mergeable state
        id: mergeable_pr
        run: |
          cat <<"EOF" > pr.json
          ${{ steps.get_pull_request_info.outputs.data }}
          EOF
          export BASE_BRANCH=$(jq -r '.base.ref' pr.json)
          echo "baseBranch=$BASE_BRANCH" >> $GITHUB_OUTPUT
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV

      - uses: octokit/request-action@v2.x
        id: get_pull_request_comments
        with:
          route: GET /repos/{repo}/issues/{pr}/comments
          repo: ${{ github.repository }}
          pr: ${{ env.PR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}

      - uses: octokit/request-action@v2.x
        id: get_maintainers_and_admins
        with:
          route: GET /repos/{owner}/{repo}/collaborators
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}

      - name: Parse maintainers and admins
        id: maintainers_and_admins_list
        run: |
          echo "$JSON_DATA" | jq -c '[.[] | select(.permissions.maintain == true or .permissions.admin == true or .permissions.push == true) | .login]' > filtered_logins.json
          echo "MAINTAINERS_AND_ADMINS=$(cat filtered_logins.json)" >> $GITHUB_OUTPUT
        env:
          JSON_DATA: ${{ steps.get_maintainers_and_admins.outputs.data }}

      - name: Check base ref, parse comments and check if fast-forward comment exists
        run: |
          if [ "$BASE_BRANCH" != "staging" ] && [ "$BASE_BRANCH" != "production" ]; then
            exit 0
          fi
          cat <<"EOF" > comments.json
          ${{ steps.get_pull_request_comments.outputs.data }}
          EOF
          COMMENT_EXISTS=$(jq -r '.[] | select(.body=="/fast-forward") | .body' < comments.json)
          echo $COMMENT_EXISTS | grep -q "/fast-forward" 2> /dev/null
          exit $?

      - name: Debug
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.event.issue.pull_request: ${{ github.event.issue.pull_request }}
          echo github.event.comment.body: ${{ github.event.comment.body }}
          echo github.event.comment.author_association: ${{ github.event.comment.author_association }}

  main:
    needs: check-for-comment
    if: >
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      github.event.comment.body == '/fast-forward' &&
      contains(fromJson(needs.check-for-comment.outputs.MAINTAINERS_AND_ADMINS), github.event.comment.user.login)
    runs-on: ubuntu-latest
    outputs:
      mergeable: ${{ steps.mergeable_pr.outputs.mergeable }}
      baseBranch: ${{ steps.mergeable_pr.outputs.baseBranch }}
      compareBranch: ${{ steps.mergeable_pr.outputs.compareBranch }}
      isProtectedBranch: ${{ steps.check_protected_branch.outputs.isProtectedBranch }}
    steps:
      - uses: octokit/request-action@v2.x
        id: get_pull_request_info
        with:
          route: GET /repos/{repo}/pulls/{pr}
          repo: ${{ github.repository }}
          pr: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}

      - name: Parse pull request using jq and checking mergeable state
        id: mergeable_pr
        run: |
          cat <<"EOF" > pr.json
          ${{ steps.get_pull_request_info.outputs.data }}
          EOF
          export IS_MERGEABLE_PR=$(jq -r '.mergeable' pr.json)
          export BASE_BRANCH=$(jq -r '.base.ref' pr.json)
          export COMPARE_BRANCH=$(jq -r '.head.ref' pr.json)
          echo "mergeable=$IS_MERGEABLE_PR" >> $GITHUB_OUTPUT
          echo "baseBranch=$BASE_BRANCH" >> $GITHUB_OUTPUT
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
          echo "compareBranch=$COMPARE_BRANCH" >> $GITHUB_OUTPUT

      - name: Check if the base ref is demo, staging or production
        id: check_protected_branch
        run: |
          if [ "${BASE_BRANCH}" != "staging" ] && [ "${BASE_BRANCH}" != "production" ]; then
            echo "isProtectedBranch=false" >> $GITHUB_OUTPUT
          else
            echo "isProtectedBranch=true" >> $GITHUB_OUTPUT
          fi

  merge:
    needs: main
    if: needs.main.outputs.mergeable == 'true' && needs.main.outputs.isProtectedBranch == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ needs.main.outputs.compareBranch }}
          token: ${{ secrets.GITHUB_AUTH_TOKEN }}

      - name: Get branch freeze status
        id: freezeStatus
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://app.mergefreeze.com/api/branches/${{ github.repository }}/${{ needs.main.outputs.baseBranch }}/?access_token=${{ secrets.MERGEFREEZE_TOKEN }}"
          method: "GET"

      - name: Unfreeze Branch
        if: fromJson(steps.freezeStatus.outputs.response).frozen
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://app.mergefreeze.com/api/branches/${{ github.repository }}/${{ needs.main.outputs.baseBranch }}/?access_token=${{ secrets.MERGEFREEZE_TOKEN }}"
          method: "POST"
          customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
          data: "frozen=false&user_name=Cerebrum MergeBot"

      - name: Wait a few seconds for the branch to be mergeable
        run: sleep 15

      - name: Merge the PR
        run: |
          git config --global user.email "smellen@cerebrum.com"
          git config --global user.name "cerebrumcom"
          # git remote set-url origin https://cerebrumcom:${{ secrets.GITHUB_AUTH_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout ${{ needs.main.outputs.baseBranch }}
          git merge --ff-only ${{ needs.main.outputs.compareBranch }}
          git push origin

      - name: Freeze Branch
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://app.mergefreeze.com/api/branches/${{ github.repository }}/${{ needs.main.outputs.baseBranch }}/?access_token=${{ secrets.MERGEFREEZE_TOKEN }}"
          method: "POST"
          customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
          data: "frozen=true&user_name=Cerebrum MergeBot"
