on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      pr_number:
        required: true
        type: number
      comment_body:
        required: true
        type: string
    secrets:
      GITHUB_AUTH_TOKEN:
        required: true
      MERGEFREEZE_TOKEN:
        required: true

jobs:
  main:
    if: ${{ inputs.comment_body == '/fast-forward' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: octokit/request-action@v2.x
        id: get_pull_request_info
        with:
          route: GET /repos/{repo}/pulls/{pr}
          repo: ${{ inputs.repo_name }}
          pr: ${{ inputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}

      - name: Parse pull request using jq and checking mergeable state
        id: mergeable_pr
        run: |
          cat <<EOF > pr.js
          ${{ steps.get_pull_request_info.outputs.data }}
          EOF
          export IS_MERGEABLE_PR=$(jq -r '.mergeable' pr.js)
          export BASE_BRANCH=$(jq -r '.base.ref' pr.js)
          export COMPARE_BRANCH=$(jq -r '.head.ref' pr.js)
          echo "mergeable=$IS_MERGEABLE_PR" >> $GITHUB_OUTPUT
          echo "baseBranch=$BASE_BRANCH" >> $GITHUB_OUTPUT
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV
          echo "compareBranch=$COMPARE_BRANCH" >> $GITHUB_OUTPUT

      - name: Check if the base ref is demo, staging or production
        run: |
          if [ "${BASE_BRANCH}" != "demo" ] && [ "${BASE_BRANCH}" != "staging" ] && [ "${BASE_BRANCH}" != "production" ]; then
            exit 1
          fi

      - uses: actions/checkout@v3
        if: steps.mergeable_pr.outputs.mergeable
        with:
          fetch-depth: 0
          ref: ${{ steps.mergeable_pr.outputs.compareBranch }}
          token: ${{ secrets.GITHUB_AUTH_TOKEN }}

      - name: Unfreeze Branch
        if: steps.mergeable_pr.outputs.mergeable
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://app.mergefreeze.com/api/branches/${{ inputs.repo_name }}/${{ env.BASE_BRANCH }}/?access_token=${{ secrets.MERGEFREEZE_TOKEN }}"
          method: "POST"
          customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
          data: "frozen=false&user_name=Cerebrum MergeBot"

      - name: Wait a few seconds for the branch to be mergeable
        run: sleep 15

      - name: Merge the PR
        if: steps.mergeable_pr.outputs.mergeable
        run: |
          git config --global user.email "smellen@cerebrum.com"
          git config --global user.name "cerebrumcom"
          # git remote set-url origin https://cerebrumcom:${{ secrets.GITHUB_AUTH_TOKEN }}@github.com/${{ inputs.repo_name }}.git
          git checkout ${{ steps.mergeable_pr.outputs.baseBranch }}
          git merge --ff-only ${{ steps.mergeable_pr.outputs.compareBranch }}
          git push origin

      - name: Freeze Branch
        if: steps.mergeable_pr.outputs.mergeable
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://app.mergefreeze.com/api/branches/${{ inputs.repo_name }}/${{ env.BASE_BRANCH }}/?access_token=${{ secrets.MERGEFREEZE_TOKEN }}"
          method: "POST"
          customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
          data: "frozen=true&user_name=Cerebrum MergeBot"
