# Automate generation of release PRs using Conventional Commits
# See https://github.com/googleapis/release-please
name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GHA_NODEJS_TOKEN }}
    steps:
      - uses: cerebruminc/ci-actions/cerebruminc/release-please@v1
        id: release
        with:
          allow-creation-of-major-and-minor-tags: true
          release-type: simple
          token: ${{ secrets.GHA_NODEJS_TOKEN }}
